# Generated by Django 3.0.5 on 2020-04-27 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=10)),
                ('emp_age', models.IntegerField()),
                ('emp_start_date', models.DateField()),
                ('emp_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Department')),
            ],
        ),
    ]
